openapi: 3.0.0
info:
  title: Blood Nation API
  description: Documentation for Blood Donation REST API
  version: 1.0.0
servers:
  - url: http://localhost:3000
tags:
  - name: donor-activities
    description: Operations related to blood donation activities
  - name: reservations
    description: Operations related to reservations for blood donation activities
paths:
  /donor-activities:
    get:
      summary: Get list of blood donation activities
      description: Retrieve a list of available, ongoing, or upcoming blood donation activities.
      tags:
        - donor-activities
      responses:
        '200':
          description: A list of blood donation activities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DonorActivity'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An internal server error occurred.

  /donor-activities/{id}:
    get:
      summary: Get details of a blood donation activity
      description: Retrieve details of a blood donation activity by its ID.
      tags:
        - donor-activities
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the blood donation activity.
      responses:
        '200':
          description: Details of the blood donation activity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DonorActivity'
        '404':
          description: Activity not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Activity not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An internal server error occurred.

  /reservations:
    get:
      summary: Get list of reservations
      description: Retrieve a list of blood donation activity reservations.
      tags:
        - reservations
      responses:
        '200':
          description: A list of reservations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Reservation'
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: You are not authorized to perform this action.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An internal server error occurred.

    post:
      summary: Create a new reservation
      description: Register for a blood donation activity by filling out the form.
      tags:
        - reservations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reservation'
      responses:
        '201':
          description: Successfully created a new reservation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reservation'
        '400':
          description: Validation errors
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: You are not authorized to perform this action.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An internal server error occurred.

  /reservations/{id}:
    put:
      summary: Update a reservation
      description: Update details of a previously made reservation.
      tags:
        - reservations
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the reservation.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reservation'
      responses:
        '200':
          description: Successfully updated the reservation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Reservation successfully updated
        '404':
          description: Reservation not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Reservation not found
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: You are not authorized to perform this action.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An internal server error occurred.

    delete:
      summary: Delete a reservation
      description: Cancel participation in a blood donation activity and delete the reservation.
      tags:
        - reservations
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          description: The ID of the reservation.
      responses:
        '200':
          description: Successfully deleted the reservation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Reservation successfully deleted
        '404':
          description: Reservation not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Reservation not found
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: You are not authorized to perform this action.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: An internal server error occurred.

components:
  schemas:
    DonorActivity:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The ID of the activity.
        location:
          type: string
          description: The location of the activity.
        quota:
          type: integer
          description: The quota of participants for the activity.
        requirements:
          type: string
          description: Requirements for donors.
        date:
          type: string
          format: date
          description: The date of the activity.
    Reservation:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: The ID of the reservation.
        activityId:
          type: string
          format: uuid
          description: The ID of the blood donation activity.
        userId:
          type: string
          format: uuid
          description: The ID of the user making the reservation.
        detailForm:
          type: string
          description: Details of the reservation form.